[package]
name = "bevy-xp"
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
