[package]
name = "lists"
edition = "2021"
license = "MIT"
version = "0.0.1"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
