version = 1

exclude_patterns = [
  "archived/**",
  "yard-rs/dx-xp/**",
  "**/main.rs"
]

# [[analyzers]]
# name = "test-coverage"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"
