# This was previously a workspace, but has been broken into individual projects.
# Each project in yard-rs/ is now a standalone Cargo project with its own Cargo.toml.
# To build all projects, use the justfile commands which iterate over each project.
