[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

# run a member with `cargo run -p member`
members = [
    "exercises/*",
    "examples/*"
]

exclude = [
    "archived/*"
]