set fallback

example_xp := justfile_directory() / "example-xp"
# CC := '/opt/homebrew/Cellar/llvm/19.1.2/bin/clang'
# CXX := '/opt/homebrew/Cellar/llvm/19.1.2/bin/clang++'
# LD := '/opt/homebrew/Cellar/llvm/19.1.2/bin/lld'
# CC := '/opt/homebrew/Cellar/llvm@18/18.1.8/bin/clang'
# CXX := '/opt/homebrew/Cellar/llvm@18/18.1.8/bin/clang++'
# LD := '/opt/homebrew/Cellar/llvm@18/18.1.8/bin/lld'
# CC := '/opt/homebrew/Cellar/llvm@17/17.0.6/bin/clang'
# CXX := '/opt/homebrew/Cellar/llvm@17/17.0.6/bin/clang++'
# LD := '/opt/homebrew/Cellar/llvm@17/17.0.6/bin/lld'
# CC := '/opt/homebrew/Cellar/gcc@13/13.3.0/bin/gcc-13'
# CXX := '/opt/homebrew/Cellar/gcc@13/13.3.0/bin/g++-13'
# LD := '/opt/homebrew/Cellar/gcc@13/13.3.0/bin/g++-13'

CC := '/home/linuxbrew/.linuxbrew/Cellar/gcc/14.2.0_1/bin/gcc-14'
CXX := '/home/linuxbrew/.linuxbrew/Cellar/gcc/14.2.0_1/bin/g++-14'
LD := `which ld`

default:
    just --list

prep-xrepo:
    curl -fsSL https://xmake.io/shget.text | bash

new NAME:
    xmake create -l c++ -P {{NAME}}

[group('ex')]
@prep-ex URL DIR BRANCH:
    #!/usr/bin/env bash
    mkdir -p {{example_xp}}
    cd {{example_xp}}
    if [[ ! -d {{example_xp / DIR}} ]]; then
        git clone --depth=100 --recurse-submodules {{URL}} {{example_xp / DIR}}
    fi
    cd {{example_xp / DIR}}
    git fetch --depth=100 origin {{BRANCH}}
    git checkout {{BRANCH}}

try-gabm: (prep-ex "https://github.com/utensil/ga-benchmark" "ga-benchmark" "master")
    cd {{example_xp / "ga-benchmark"}}

[no-cd]
build:
    xmake f --toolchain=gcc --cxx={{CXX}} --cc={{CC}} --ld={{LD}}
    # xmake f --toolchain=clang --cxx={{CXX}} --cc={{CC}} --ld={{LD}}
    xmake -vv
 
[no-cd]
run: build
    xmake run

[no-cd]
clean:
    xmake clean -a
    xmake f --clean
