[package]
# [Rust: The Basics](https://stepik.org/lesson/9268/)
name = "rust_basics"
authors = ["utensil <utensilcandel@gmail.com>"]
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[dependencies]
assert_cli = "0.6.3"
maplit = "1.0.1"
chrono = "0.4"
