[package]
# [Rust: The Basics](https://stepik.org/lesson/9268/)
name = "rust_basics"
authors = ["utensil <utensilcandel@gmail.com>"]
edition = "2021"
license = "MIT"
version = "0.0.1"
publish = false

[dependencies]
assert_cli = "0.6.3"
maplit = "1.0.1"
chrono = "0.4"
