[toolchain]
channel = "nightly-2023-05-27"
# channel = "stable"
profile = "default"
components = [
	"rust-src",
	"rustc-dev",
	"llvm-tools-preview",
	"clippy",
	"rustfmt",
	"rustc",
    "rust-analyzer"
]
