run:
    xmake -y -v && xmake run

clean:
    xmake clean

prep-vcpkg:
    git clone https://github.com/microsoft/vcpkg "$HOME/.vcpkghome"
    cd "$HOME/.vcpkghome" && ./bootstrap-vcpkg.sh
    @echo >> ~/.zshrc
    @echo "export VCPKG_ROOT=$HOME/.vcpkghome" >> ~/.zshrc
    @echo "export PATH=\$VCPKG_ROOT:\$PATH" >> ~/.zshrc
    @echo "Run: source ~/.zshrc"

prep-conan:
    brew install conan
    # conan profile new default --detect
    # conan profile update settings.compiler.libcxx=libstdc++11 default
    # conan profile update settings.compiler.cppstd=20 default

prep-conda:
    brew install --cask miniforge
    # brew install --cask miniconda
    # brew install --cask anaconda
    # brew install micromamba

@find NAME:
    xmake require -v --search {{NAME}} || true
    xmake require -v --search "vcpkg::{{NAME}}" || true
    xmake require -v --search "conan::{{NAME}}" || true
    xmake require -v --search "conda::{{NAME}}" || true
    # xmake require --search "clib::{{NAME}}" || true
    # xmake require --search "brew::{{NAME}}" || true

@info NAME:
    xmake require --info {{NAME}}

@fetch NAME:
    xmake require --fetch {{NAME}}

@list:
    xmake require --list