name: monit-runpod

permissions:
    actions: write

on:
  schedule:
  - cron: "* * * * *"

jobs:
  monit:
    name: monit-runpod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.6.1
      with:
        python-version: 3.x
        cache: pip
        cache-dependency-path: yard-rs/runpod-xp/requirements-runpod.txt
    - name: Monit
      run: |
        cd yard-rs/runpod-xp
        just prep-runpod
        just monit-runpod
      env:
        RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GH_TOKEN: ${{ github.token }}