# this project is adapted from
# - https://github.com/GraphiteEditor/Graphite/tree/master/node-graph/gpu-compiler
# - https://github.com/Rust-GPU/rust-gpu/blob/main/examples/runners/wgpu/build.rs
[workspace]

[package]
name = "rsgpu-runner-xp"
version = "0.1.0"

[dependencies]