default:
    just --list

prep-dx:
    cargo install dioxus-cli
    @echo "create a new project: dx new"

dx-new:
    dx new

dx-css:
    cd {{invocation_directory()}}; bunx tailwindcss -i ./input.css -o ./assets/tailwind.css --watch
dx-dev:
    cd {{invocation_directory()}}; dx serve --hot-reload --platform desktop
dx-test: dx-prep-test
    cd {{invocation_directory()}}; cargo test
dx-prep-test:
    cd {{invocation_directory()}}; cargo add dioxus-ssr pretty_assertions futures