[package]
name = "rust_cpp"
build = "build.rs"
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[dependencies]
assert_cli = "0.6.3"
maplit = "1.0.1"
cpp = "0.5"
chrono = "0.4"

[build-dependencies]
cpp_build = "0.5"
cc = "1.0"
