[package]
name = "rust_cpp"
build = "build.rs"
edition = "2021"
license = "MIT"
readme = "README.md"
version = "0.0.1"

[dependencies]
assert_cli = "0.6.3"
maplit = "1.0.1"
cpp = "0.5"
chrono = "0.4"

[build-dependencies]
cpp_build = "0.5"
cc = "1.0"
