[workspace]
[package]
name = "rust_cpp"
version = "0.0.1"
authors = ["utensil <utensilcandel@gmail.com>"]
build = "build.rs"

[dependencies]
assert_cli = "0.6.3"
maplit = "1.0.1"
cpp = "0.4"
chrono = "0.4"

[build-dependencies]
cpp_build = "0.4"
cc = "1.0"