name: runpod-monit

permissions:
    actions: write

on:
  workflow_dispatch:
  schedule:
  # https://stackoverflow.com/a/60095391/200764
  # The shortest interval you can run scheduled workflows is once every 5 minutes.
  - cron: "*/5 * * * *"

jobs:
  monit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2
      with:
        just-version: 1.36.0
    - name: Setup Python via uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.27"
        enable-cache: true
    - name: Monit
      run: |
        cd yard-rs/runpod-xp
        just monit
      env:
        RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GH_TOKEN: ${{ github.token }}
