name: runpod-monit

permissions:
    actions: write

on:
  workflow_dispatch:
  schedule:
  # https://stackoverflow.com/a/60095391/200764
  # The shortest interval you can run scheduled workflows is once every 5 minutes.
  - cron: "*/5 * * * *"

jobs:
  monit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v1
      with:
        just-version: 1.36.0
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: yard-rs/runpod-xp/requirements-runpod.txt
    - name: Monit
      run: |
        cd yard-rs/runpod-xp
        just prep
        just monit
      env:
        RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GH_TOKEN: ${{ github.token }}