name: CI (Zig)

on:
  push:
    branches: [main]
    paths:
      - "yard-zig/basic-xp/**"
  pull_request:
    branches: [main]
    paths:
      - "yard-zig/basic-xp/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v4
      - name: Install Zig
        run: |
          cd yard-zig/basic-xp
          just prep-asdf
          asdf install
      - name: Run tests
        run: |
          export PATH="$HOME/.asdf/shims:$PATH"
          cd yard-zig/basic-xp
          just test
