name: CI (Zig)

on:
  push:
    branches: [main]
    paths:
      - "yard-zig/basic-xp/**"
      - "yard-zig/justfile"
      - ".github/workflows/zig.yml"
      - "!.deepsource.toml"
      - "!**/README.md"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v4
        with:
          asdf_branch: v0.15.0
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.39.0
      - name: Install Zig
        run: |
          cd yard-zig/basic-xp
          just prep-asdf
          asdf install
      - name: Run tests
        run: |
          export PATH="$HOME/.asdf/shims:$PATH"
          cd yard-zig/basic-xp
          just test
