name: CI (Zig)

on:
  push:
    branches: [main]
    paths:
      - "yard-zig/basic-xp/**"
      - "yard-zig/justfile"
      - ".github/workflows/zig.yml"
      - "!.deepsource.toml"
      - "!**/README.md"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1.39.0,mise
      - name: Install Zig
        run: |
          cd yard-zig/basic-xp
          mise install
      - name: Run tests
        run: |
          cd yard-zig/basic-xp
          eval "$(mise activate bash)"
          just test
